<?php

def('LIMNY_ADMINISTRATION', 'مدیریت لیمنی');
def('USERNAME', 'نام‌کاربری');
def('PASSWORD', 'گذرواژه');
def('REMEMBER_ME', 'مرا به خاطر بسپار');
def('SIGN_IN', 'ورود');
def('DASHBOARD', 'پیشخوان');
def('UPDATE', 'بروزرسانی');
def('VISIBILITY', 'پدیداری');
def('BLOCKS', 'بلاک‌ها');
def('WIDGETS', 'ابزارک‌ها');
def('THEMES', 'زمینه‌ها');
def('USERS', 'کاربران');
def('ROLES', 'نقش‌ها');
def('APPLICATIONS', 'برنامه‌ها');
def('CONFIGURATION', 'پیکربندی');
def('TITLE', 'عنوان');
def('MOTTO', 'شعار');
def('DESCRIPTION', 'توضیحات');
def('HEADER', 'سرصفحه');
def('FOOTER', 'پانویس');
def('CACHE_LIFETIME', 'عمر کش');
def('DEFAULT_CONTENT', 'محتوای پیش‌فرض');
def('APPLICATION', 'برنامه');
def('QUERY', 'جستار');
def('TEXT', 'متن');
def('LANGUAGE', 'زبان');
def('UNINSTALLED', 'نصب‌نشده');
def('INSTALL', 'نصب');
def('INSTALLED', 'نصب‌شده');
def('UNINSTALL', 'حذف‌کردن');
def('YES', 'بله');
def('NO', 'خبر');
def('DEPENDS_ON', 'وابسته به');
def('REQUIRED_BY', 'مورد نیاز توسط');
def('NOT_COMPATIBLE', 'سازگار نیست');
def('BY', 'توسط');
def('SET_AS_DEFAULT', 'تنظیم پیش‌فرض');
def('EDIT', 'ویرایش');
def('ERROR', 'خطا');
def('SAVE_CHANGES', 'ذخیره تغییرات');
def('SAVING', 'در حال ذخیره');
def('PREVIEW', 'پیش‌نمایش');
def('TIME_ZONE', 'موقعیت زمانی');
def('CURRENT_DATE_TIME', 'تاریخ/ساعت فعلی');
def('FILE', 'پرونده');
def('INSTALL_NEW', 'نصب تازه');
def('EMAIL', 'رایانامه');
def('STATUS', 'وضعیت');
def('LAST_ACTIVITY', 'آخرین فعالیت');
def('NEVER', 'هرگز');
def('SECOND', 'ثانیه');
def('MINUTE', 'دقیقه');
def('HOUR', 'ساعت');
def('DAY', 'روز');
def('WEEK', 'هفته');
def('MONTH', 'ماه');
def('YEAR', 'سال');
def('DECADE', 'دهه');
def('PLURAL_S', '');
def('AGO', 'پیش');
def('ENABLE', 'فعال');
def('DISABLE', 'غیرفعال');
def('_DEFAULT_', 'پیش‌فرض');
def('ID', 'ردیف');
def('THEME', 'زمینه‌');
def('LAST_IP', 'آخرین آی‌پی');
def('LAST_LOGIN', 'آخرین ورود');
def('NAME', 'نام');
def('PERMISSIONS', 'مجوزها');
def('ADMIN', 'مدیریت');
def('APP', 'برنامه');
def('SIGN_OUT', 'بیرون‌رفتن');
def('PROFILE', 'نیم‌رخ');
def('NICK_NAME', 'نام خودمانی');
def('FIRST_NAME', 'نام');
def('LAST_NAME', 'نام خانوادگی');
def('NEW_PASSWORD', 'گذرواژه تازه');
def('REPEAT_NEW_PASSWORD', 'تکرار گذرواژه تازه');
def('MENU', 'فهرست');
def('TOOLTIP', 'متن‌راهنما');
def('ADDRESS', 'نشانی');
def('NEW_WINDOW', 'پنجره تازه');
def('ORDER', 'ترتیب');
def('CALENDAR', 'تقویم');
def('GREGORIAN', 'میلادی');
def('SOLAR_HIJRI', 'هجری شمسی');
def('DATE_FORMAT', 'نوع تاریخ');
def('USER_REGISTRATION', 'نام‌نویسی کاربران');
def('URL_MODE', 'حالت URL');
def('SIMPLE', 'اسده');
def('STANDARD', 'استاندارد');
def('EMAIL_CONFIRMATION', 'تائید رایانامه');
def('SORT', 'مرتب‌سازی');
def('NOTIFICATIONS', 'یادآوری‌ها');
def('UNSIGNED', 'وارد نشده');
def('CHANGE', 'تغییر');
def('SMTP_HOST', 'میزبان SMTP');
def('SMTP_PORT', 'درگاه SMTP');
def('SMTP_SECURITY', 'امنیت SMTP');
def('SMTP_AUTHENTICATION', 'احراز هویت SMTP');
def('YES', 'بله');
def('NO', 'خبر');
def('SMTP_USERNAME', 'نام کاربری SMTP');
def('SMTP_PASSWORD', 'گذرواژه SMTP');

def('SENTENCE_1', 'لطفا نام‌کاربری خود را وارد کنید.');
def('SENTENCE_2', 'لطفا گذرواژه خود را وارد کنید.');
def('SENTENCE_3', 'نام‌کاربری یا گذرواژه معتبر نیستند.');
def('SENTENCE_4', 'بیشینه عمر برای کش صفحات');
def('SENTENCE_5', 'پیکربندی با موفقیت بروزرسانی شد.');
def('SENTENCE_6', 'هیچ برنامه‌ای نصب نشده‌است.');
def('SENTENCE_7', 'همه داده‌ها از دست خواهند رفت، آیا مطمئن هستید؟');
def('SENTENCE_8', 'هیچ زمینه‌ای پیدا نشد.');
def('SENTENCE_9', 'زمینه پیدا نشد.');
def('SENTENCE_10', 'هیچ تغییری انجام نشده است.');
def('SENTENCE_11', 'خطا در ذخیره تغییرات.');
def('SENTENCE_12', 'با موفقیت ذخیره شد.');
def('SENTENCE_13', 'هیچ ابزارکی نصب نشده است.');
def('SENTENCE_14', 'فقط پرونده ابزارک فشرده شده (.zip)');
def('SENTENCE_15', 'فقط بایگانی زیپ قابل قبول است.');
def('SENTENCE_16', 'ابزارک حذف خواهد شد، آیا مطمئن هستید؟');
def('SENTENCE_17', 'بایگانی زیپ قابل باز شدن نیست.');
def('SENTENCE_18', 'بایگانی زیپ خالی است.');
def('SENTENCE_19', 'پرونده‌های ابزارک در این بایگانی پیدا نشدند.');
def('SENTENCE_20', 'این نام‌کاربری قبلا انتخاب شده است.');
def('SENTENCE_21', 'اگر نمی‌خواهید تغییر دهید خالی بگذارید.');
def('SENTENCE_22', 'نام‌کاربری باید شامل کمینه ۳ نویسه باشد.');
def('SENTENCE_23', 'نام‌کاربری فقط می‌تواند شامل نویسه‌های حرف و عدد باشد.');
def('SENTENCE_24', 'گذرواژه باید شامل بیشینه ۶ نویسه باشد.');
def('SENTENCE_25', 'این رایانامه قبلا انتخاب شده است.');
def('SENTENCE_26', 'این رایانامه معتبر نیست.');
def('SENTENCE_27', 'نیم‌رخ با موفقیت بروزرسانی شد.');
def('SENTENCE_28', 'گذرواژه‌های تازه یکی نیستند.');
def('SENTENCE_29', 'گذرواژه درست نیست.');
def('SENTENCE_30', 'ساختار تاریخ PHP: http://php.net/manual/en/function.date.php');
def('SENTENCE_31', 'این صفحه وجود ندارد یا اینکه حساب کاربری شما مجوز کافی برای دسترسی به این صفحه را ندارد.');
def('SENTENCE_32', 'صفحه پیدا نشد یا اینکه برنامه هنوز نصب نشده‌اسد.');
def('SENTENCE_33', 'صفحه برنامه پیدا نشد.');
def('SENTENCE_34', 'هیچ یادآوری وجود ندارد.');
def('SENTENCE_35', 'این تنظیم توسط امنیت غیرفعال شده است');
def('SENTENCE_36', 'برای پیوند به صفخات داخلی نام برنامه یا صفحه را درون [] قرار دهید.');

?>